[package]
name = "pitchfork"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolector = { path = "../boolector-rs" }
haybale = { path = "../haybale" }
llvm-ir = "0.3.2"
log = "0.4.8"
env_logger = "0.6.2"
itertools = "0.8.2"
either = "1.5.3"
