[package]
name = "pitchfork"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolector = "0.1.2"
haybale = { path = "../haybale" }
llvm-ir = "0.5.0"
log = "0.4.8"
env_logger = "0.6.2"
lazy_static = "1.4"
colored = "1.9"
itertools = "0.8.2"
either = "1.5.3"
