[package]
name = "haybale-pitchfork"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"
description = "Verifying constant-time code with symbolic execution"
documentation = "https://PLSysSec.github.io/haybale-pitchfork"
repository = "https://github.com/PLSysSec/haybale-pitchfork"
readme = "README.md"
keywords = ["constant-time", "symbolic", "llvm", "SMT"]
license = "MIT"

[dependencies]
boolector = "0.3.0"
haybale = { git = "https://github.com/PLSysSec/haybale", branch = "eventually-0.4.0" }
llvm-ir = "0.5.0"
log = "0.4.8"
lazy_static = "1.4"
colored = "1.9"
itertools = "0.8.2"
either = "1.5.3"
chrono = "0.4"

[dev-dependencies]
env_logger = "0.6.2"
