[package]
name = "pitchfork"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolector = { path = "../boolector-rs" }
haybale = { path = "../haybale" }
llvm-ir = { git = "https://github.com/cdisselkoen/llvm-ir" }
log = "0.4.0"
env_logger = "0.6.1"
